name = "client"
version = "1.0.0"
target = "javascript"

[dependencies]
client_sdk = { path = "../../packages/client_sdk" }
common = { path = "../../packages/common" }
go_api = { path = "../../packages/go_api" }

gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.7.1 and < 6.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_http = ">= 4.4.0 and < 5.0.0"
gleam_time = ">= 1.11.0 and < 2.0.0"
plinth = ">= 0.11.0 and < 1.0.0"
rsvp = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.6 and < 3.0.0"

[tools.lustre.build]
minifi = true
outdir = "../server/priv/static" 

[tools.lustre.dev]
host = "0.0.0.0"
proxy = { from = "/api", to = "http://localhost:3000/api" }
